# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fizalihsan.github.io" # the base hostname & protocol for your site
twitter_username: @fizalihsan
github_username:  fizalihsan

# Markdown Processors
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

# Build settings
highlighter: true
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
permalink: pretty

timezone: America/New_York

# Local http port to publish
port: 4000
